### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by AbdulkodirBurganov** [Samirox66/hotel#1]
Папка .vscode содержит настройки проекта именно VSCode и подобные папки лучше кидать в .gitignore

**Comment by AbdulkodirBurganov** [comment]
Это относится и к node_modules. Вот небольшая статья об этом, если интересно: https://flaviocopes.com/should-commit-node-modules-git/

**Comment by Samirox66** [comment]
Видимо, поздно добавил их в .gitignore
